# Generated by Django 5.2.4 on 2025-07-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('map_embed', models.TextField(blank=True, verbose_name='Карта (iframe)')),
                ('working_hours', models.CharField(blank=True, max_length=255, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('title', models.CharField(max_length=55, verbose_name='Название')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('views', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Просмотры')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='PodcastChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('image', models.ImageField(upload_to='podcast/channel-images/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Подкаст',
                'verbose_name_plural': 'Подкасты',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('type', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('threads', 'Threads'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube')], max_length=15)),
                ('url', models.URLField()),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('image', models.ImageField(upload_to='podcast/release-images/', verbose_name='Изображение')),
                ('audio', models.FileField(upload_to='podcast/releases/', verbose_name='Аудио')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.podcastchannel')),
            ],
            options={
                'verbose_name': 'Выпуск подкаста',
                'verbose_name_plural': 'Выпуски подкаста',
            },
        ),
    ]
