# Generated by Django 5.2.4 on 2025-07-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_socialnetwork_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=55)),
                ('url', models.URLField(blank=True)),
                ('photo', models.ImageField(upload_to='banner-photos/')),
                ('btn_text', models.CharField(max_length=15)),
            ],
        ),
    ]
