# Generated by Django 5.2.4 on 2025-07-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainslider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainslider',
            old_name='photo',
            new_name='image',
        ),
    ]
