# Generated by Django 5.2.4 on 2025-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_photo_mainslider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastchannel',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='podcastrelease',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='podcastrelease',
            name='image',
            field=models.ImageField(default='defaults/podcast-release.jpg', upload_to='podcast/release-images/', verbose_name='Изображение'),
        ),
    ]
