# Generated by Django 5.2.4 on 2025-07-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_podcastchannel_youtube_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcastrelease',
            old_name='youtube_url',
            new_name='youtube_id',
        ),
    ]
