# Generated by Django 5.2.4 on 2025-07-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_youtube_url_podcastrelease_youtube_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastrelease',
            name='audio',
        ),
        migrations.AlterField(
            model_name='podcastrelease',
            name='youtube_id',
            field=models.CharField(max_length=255),
        ),
    ]
